# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Courses/COD实验/zy_lab4/zy_lab4.srcs/sources_1/ip/I_mem1/I_mem1.xci
# IP: The module: 'I_mem1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Courses/COD实验/zy_lab4/zy_lab4.srcs/sources_1/ip/I_mem1/I_mem1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I_mem1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Courses/COD实验/zy_lab4/zy_lab4.srcs/sources_1/ip/I_mem1/I_mem1.xci
# IP: The module: 'I_mem1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Courses/COD实验/zy_lab4/zy_lab4.srcs/sources_1/ip/I_mem1/I_mem1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I_mem1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
