# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: top.xdc

# IP: D:/Courses/COD/CPU_2/CPU_2.ip_user_files/D_mem_1/D_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==D_mem || ORIG_REF_NAME==D_mem} -quiet] -quiet
