# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/13232/Desktop/vivado/zy_lab4/zy_lab4.srcs/sources_1/ip/D_mem1/D_mem1.xci
# IP: The module: 'D_mem1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/13232/Desktop/vivado/zy_lab4/zy_lab4.srcs/sources_1/ip/D_mem1/D_mem1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'D_mem1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/13232/Desktop/vivado/zy_lab4/zy_lab4.srcs/sources_1/ip/D_mem1/D_mem1.xci
# IP: The module: 'D_mem1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/13232/Desktop/vivado/zy_lab4/zy_lab4.srcs/sources_1/ip/D_mem1/D_mem1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'D_mem1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
