# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.cache/wt [current_project]
set_property parent.project_path C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/TempDesktop/test_ins/hazard.coe
add_files d:/TempDesktop/test_ins/test.coe
add_files d:/TempDesktop/test_ins/data.coe
add_files d:/TempDesktop/test_ins/sort_data.coe
add_files d:/TempDesktop/test_ins/sort_text.coe
add_files d:/TempDesktop/test_ins/float_text.coe
add_files d:/TempDesktop/test_ins/float_data.coe
add_files d:/TempDesktop/test_ins/sortF_text.coe
add_files d:/TempDesktop/test_ins/sortF_data.coe
add_files d:/TempDesktop/test_ins/test1.coe
read_verilog -library xil_defaultlib {
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/ALU.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/ALU_control.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/Add.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/new/Branch_unit.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/CPU.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/new/Forwarding_unit.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/new/Hazard_detection_unit.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/ImmGen.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/Mux.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/new/PC.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/Registers.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/Shift_left.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/new/compareF.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/control.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/pdu_pl.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/new/reg_offset.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/segment_register.v
  C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/imports/sources_1/imports/new/CPU_PL.v
}
read_ip -quiet C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc]

read_ip -quiet C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/constrs_1/imports/verilog/seg_fpgaol.xdc
set_property used_in_implementation false [get_files C:/Users/chenzhiyuan/source/vscode/verilog/comprehensive_designing/comprehensive_designing.srcs/constrs_1/imports/verilog/seg_fpgaol.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top test -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
